### ISSUE TITLE
Prompt del path del archivo `meta.json` al usuario

### ISSUE THREAD

**Issue by neowinx** [neowinx/generator-restful-vue-bulma#10]
Se podría agregar un paso más durante la config del generador para proveer el path al archivo `meta.json` a utilizar, ya que actualmente el  archivo debe estar en el mismo contexto que el generador.

**Comment by ldbenitez** [comment]
El paso adicional para indicar el path al archivo meta json de configuración ha sido atendido en el pull request  #13
