### ISSUE TITLE
Add meta.json specifiation to README.md

### ISSUE THREAD

**Issue by neowinx** [neowinx/generator-restful-vue-bulma#8]
There are some undocumented features of the use of meta.json files with this generator.

We need to traverse the code in [generators/crud/templates/View.vue.ejs](https://github.com/neowinx/generator-restful-vue-bulma/blob/master/generators/crud/templates/View.vue.ejs) and document the reference and usage of the `[serviceName].meta.json` acording of what does what

**Comment by ldbenitez** [comment]
A traverse of the code from View.vue.ejs was done. The readme now includes a brief introduction to the CRUD sub-generator as well as options available to use on meta json config files. See 7f3bcb3f53ea3df14d2ff9a6e68b7dc5dbc3fbf5
